# Generated by Django 2.1b1 on 2018-07-09 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_forum', '0014_auto_20170208_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=models.SET(None), related_name='attachments_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(on_delete=models.SET(None), related_name='commented_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertopics',
            name='topic',
            field=models.ForeignKey(on_delete=models.SET(None), to='django_simple_forum.Topic'),
        ),
        migrations.AlterField(
            model_name='usertopics',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
    ]
